apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: plausible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy
          command: ["caddy", "reverse-proxy", "--from", "$(FROM_URL)", "--to", "http://plausible:8000"]
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: DOMAIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: plausible-config
                  key: DOMAIN_NAME
            - name: FROM_URL
              value: "https://$(DOMAIN_NAME):443"

---

apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: plausible
spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
