apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: plausible
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:14-alpine
          envFrom:
            - configMapRef:
                name: plausible-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: plausible
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
